name = "thyme-by-vine"
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./build/client"

[[d1_databases]]
binding = "DB"
database_name = "thyme-by-vine-db"
database_id = "01ec1c99-d165-4e40-908e-70d7bcf01cf0"

[vars]
APP_URL = "http://localhost:5173"
STRIPE_PUBLISHABLE_KEY = "pk_test_placeholder_replace_with_your_key"
